export const ERROR_CONSUMED = 'ERROR_CONSUMED';
export const ERROR_FLICKR = 'FLICKR_ERROR';

export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const PHOTOS_LOADING_SUCCESS = 'PHOTOS_LOADING_SUCCESS';